service: guane-test-infrastructure

frameworkVersion: '2'

custom:
  default_stage: dev
  active: ${file(conf.${self:provider.stage}.yml):conf}  

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.default_stage}
  region: ${self:custom.active.REGION}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        Fn::Join:
          - /
          - - Fn::GetAtt:
                - FrontWebsiteBucket
                - Arn
            - '*'

resources:
  - ${file(./resources/lambdaiamrole.yml)} 
  - ${file(./resources/lambdaedge.yml)} 
  - ${file(./resources/websitebucket.yml)}
  - ${file(./resources/cloudfrond.yml)}
